var TITLE = "【FATE】耶路撒冷聖杯戰爭";
var INDEX = [
	{ title: "第零章：起始", members: [
		{ title: "0-1. 召喚夜", url: "Jerusalem_part01.html" },
		{ title: "0-2. 兩人的計畫", url: "Jerusalem_part02.html" },
	] },
	{ title: "第一章：布局", members: [
		{ title: "1-1. 黃雀在後?", url: "Jerusalem_part03.html" },
		{ title: "1-2. 美少女從者", url: "Jerusalem_part04.html" },
		{ title: "1-3. 公園遇襲", url: "Jerusalem_part05.html" },
		{ title: "1-4. 祈雨儀式", url: "Jerusalem_part06.html" },
		{ title: "1-5. 女傀儡使", url: "Jerusalem_part07.html" },
		{ title: "1-6. Lancer 與 Archer", url: "Jerusalem_part08.html" },
		{ title: "1-7. Saber", url: "Jerusalem_part09.html" },
	] },
	{ title: "第二章：前哨戰", members: [
		{ title: "2-1. 未來視與危機", url: "Jerusalem_part10.html" },
		{ title: "2-2. 據點的入侵者", url: "Jerusalem_part11.html" },
		{ title: "2-3. 崩塌的大樓", url: "Jerusalem_part12.html" },
		{ title: "2-4. 少年的邀請", url: "Jerusalem_part13.html" },
		{ title: "2-5. 槍者的訓練", url: "Jerusalem_part14.html" },
		{ title: "2-6. 夜．夢", url: "Jerusalem_part15.html" },
	] },
	{ title: "第三章：同盟", members: [
		{ title: "3-1. 之後的策略", url: "Jerusalem_part16.html" },
		{ title: "3-2. 第二日的事前調查", url: "Jerusalem_part17.html" },
		{ title: "3-3. 以色列總部，閒聊", url: "Jerusalem_part18.html" },
		{ title: "3-4. 同盟的會談", url: "Jerusalem_part19.html" },
		{ title: "3-5. 舊城紛爭", url: "Jerusalem_part20.html" },
		{ title: "3-6. 神祕女子法蒂妮", url: "Jerusalem_part21.html" },
		{ title: "3-7. 橄欖山的戰鬥", url: "Jerusalem_part22.html" },
		{ title: "3-8. 瑪卡賽德醫院．Berserker 的真身", url: "Jerusalem_part23.html" },
		{ title: "3-9. 艾米．席凡斯", url: "Jerusalem_part24.html" },
		{ title: "3-10. Rider 的準備", url: "Jerusalem_part25.html" },
		{ title: "3-11. 大戰前的最後會面", url: "Jerusalem_part26.html" },		
	] },
	{ title: "第四章：衝突", members: [
		{ title: "4-1. 與泰勒沙相談", url: "Jerusalem_part27.html", },
		{ title: "4-2. 與Berserker的決戰", url: "Jerusalem_part28.html", },
		{ title: "4-3. 情況生變", url: "Jerusalem_part29.html", },
		{ title: "4-4. 第七個人的令咒與決裂", url: "Jerusalem_part30.html", },
		{ title: "4-5. 向瑪莉亞伸出的手", url: "Jerusalem_part31.html", },
		{ title: "4-6. 令咒移植、告別、與聖杯", url: "Jerusalem_part32.html", },	
	] },
	{ title: "第五章：劇變", members: [
		{ title: "5-1. 第二次的召喚儀式", url: "Jerusalem_part33.html", },
		{ title: "5-2. Rider．決裂", url: "Jerusalem_part34.html", },
		{ title: "5-3. 兩方的準備", url: "Jerusalem_part35.html", },
		{ title: "5-4. 菲力克斯的背叛", url: "Jerusalem_part36.html", },
		{ title: "5-5. 紅衣主教的願望", url: "Jerusalem_part37.html", },
		{ title: "5-6. 索拉的末路", url: "Jerusalem_part38.html", },
		{ title: "5-7. 聖殿山上的決鬥", url: "Jerusalem_part39.html", },
		{ title: "5-8. 靈魂之井", url: "Jerusalem_part40.html", },
		{ title: "5-9. 掠奪王 Raider", url: "Jerusalem_part41.html", },	
	] },
	{ title: "第六章：回憶", members: [
		{ title: "6-1. 昔日", url: "Jerusalem_part42.html", },
		{ title: "6-2. 深夜與老友會晤", url: "Jerusalem_part43.html", },
		{ title: "6-3. 夜．空虛的夢", url: "Jerusalem_part44.html", },	
	] },
	{ title: "第七章：決戰", members: [
		{ title: "7-1. 最後的聯盟作戰", url: "Jerusalem_part45.html", },
		{ title: "7-2. 終戰前", url: "Jerusalem_part46.html", },
		{ title: "7-3. 在這同時，索拉", url: "Jerusalem_part47.html", },
		{ title: "7-4. 亂戰後的殘局", url: "Jerusalem_part48.html", },
		{ title: "7-5. 決裂的摯友", url: "Jerusalem_part49.html", },
		{ title: "7-6. 聖杯戰爭的最後一戰", url: "Jerusalem_part50.html", },
		{ title: "7-7. 神話衝突", url: "Jerusalem_part51.html", },
		{ title: "7-8. 向這聖地獻上祈願", url: "Jerusalem_part52.html", },	
	] },
	{ title: "EP-1. 世界的巡禮", url: "Jerusalem_part53.html", },
	{ title: "EP-2. 無慾者的末路", url: "Jerusalem_part54.html", },
];